### ISSUE TITLE
Make a branch for us to place our additional patches etc. onto

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/linux#2]
Our master branch is trackining the mainline kernel - we need a branch where we apply our config and small set of patches on top of.
We should probably define a naming scheme for the branches. Possibly just appending 'kata' to the end of the kernel version/tag will work - so we would be on branch 'v4.13.13-kata' when #1 lands for instance?

**Comment by devimc** [comment]
https://github.com/kata-containers/linux/tree/linux-kata-containers-4.13.3

**Comment by grahamwhaley** [comment]
Closing this now we have the branch.
