### ISSUE TITLE
Switch to 4.14

### ISSUE THREAD

**Issue by sameo** [kata-containers/linux#6]
4.14 is the latest stable branch. We should switch from 4.13.3 to 4.14.13.

**Comment by sameo** [comment]
cc @gnawux @bergwolf

**Comment by gnawux** [comment]
+1
When we set to 4.13, we had talked we would move to 4.14 lts after it was out.

**Comment by WeiZhang555** [comment]
+1

**Comment by egernst** [comment]
This is done already.  Closing...
