### ISSUE TITLE
Archive this repository

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/linux#8]
As discussed and agreed on https://github.com/kata-containers/qemu/issues/10, we're archiving this repository - it isn't used any more. See:

- https://github.com/kata-containers/packaging/tree/master/kernel

**Comment by jodh-intel** [comment]
@fidencio - thanks for closing. Are you planning to actually archive the repo though?

**Comment by fidencio** [comment]
No, I'm planning to revive it as we will need to host a specific kernel repo for the Confidential Containers effort.

**Comment by jodh-intel** [comment]
Thanks - that now explains why you closed the issue ;)
